<a href="https://colab.research.google.com/github/satyavenkat2011/ANN-EXPERIMENTS/blob/main/pythonbasicsANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***square root of two numbers***

In [ ]:
a=int(input())

4


In [ ]:
import math
squareroot=math.sqrt(a)


In [ ]:
print(squareroot)

2.0


# **code to swap two numbers**

In [ ]:
f1=int(input("enter first number"))
f2=int(input("enter second number"))


enter first number34
enter second number89


In [ ]:
temp=f1
f1=f2
f2=temp
print(f"{f1} {f2}")

89 34


# ***check positive negative or 0***

In [ ]:
num = int(input("enter the number you want to check"))
if(num>0):
  print("The given number is positive")
elif(num<0):
  print("The given number is negative")
else:
  print("The given number is '0' ")

enter the number you want to check0
The given number is '0' 


# ***given number is odd or even***

In [ ]:
n=int(input())
if(n%2==0):
  print("Even")
else:
  print("Odd")

45
Odd


# ***find factorial***

In [ ]:
fact=int(input("Enter number"))
x=1
while(fact>0):
  x=x*fact
  fact=fact-1
print(x)


Enter number4
24


# ***weather a given string is a palindrome or not***

In [ ]:
string=input("Enter a string ")
rev=string[::-1]
if(string==rev):
  print(f"{string} is a pallindrome")
else:
  print(f"{string} is Not a pallindrome")


Enter a string dad
dad is a pallindrome


# ***calendar***

In [ ]:
import calendar
yyyy=int(input("Enter a year  "))
mm=int(input("Enter a month  "))
print(calendar.month(yyyy,mm))


Enter a year  2024
Enter a month  3
     March 2024
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



### ***McCulloch-Pitts Model of Neuron, And gate***

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam





In [ ]:
x=np.array([[0,0,0],
           [0,0,1],
           [0,1,0],
           [0,1,1],
           [1,0,0],
           [1,0,1],
           [1,1,0],
           [1,1,1]])
y=np.array([[0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [0],
           [1]])


In [ ]:
model=Sequential(Dense(1,input_dim=3,activation='sigmoid'))
model.compile(optimizer=Adam(learning_rate=0.1),loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(x,y,epochs=100,verbose=0)

In [ ]:
for i in x:
  prediction=model.predict(np.array([i]))
  print(f"input:{i} -prediction: {round(prediction.flatten()[0])} ")

1/1 [==============================] - 0s 21ms/step
input:[0 0 0] -prediction: 0 
1/1 [==============================] - 0s 20ms/step
input:[0 0 1] -prediction: 0 
1/1 [==============================] - 0s 19ms/step
input:[0 1 0] -prediction: 0 
1/1 [==============================] - 0s 22ms/step
input:[0 1 1] -prediction: 0 
1/1 [==============================] - 0s 24ms/step
input:[1 0 0] -prediction: 0 
1/1 [==============================] - 0s 19ms/step
input:[1 0 1] -prediction: 0 
1/1 [==============================] - 0s 27ms/step
input:[1 1 0] -prediction: 0 
1/1 [==============================] - 0s 21ms/step
input:[1 1 1] -prediction: 1 


# ***McCulloch-Pitts Model of Neuron , Or Gate***

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [ ]:
x=np.array([[0,0,0],
           [0,0,1],
           [0,1,0],
           [0,1,1],
           [1,0,0],
           [1,0,1],
           [1,1,0],
           [1,1,1]])
y=np.array([[0],
            [1],
            [1],
            [1],
            [1],
            [1],
            [1],
            [1],])

In [ ]:
model=Sequential(Dense(1,input_dim=3,activation='sigmoid'))
model.compile(optimizer=Adam(learning_rate=0.1),loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(x,y,epochs=100,verbose=1)

Epoch 1/100
1/1 [==============================] - 1s 873ms/step - loss: 0.4517 - accuracy: 1.0000
Epoch 2/100
1/1 [==============================] - 0s 10ms/step - loss: 0.3891 - accuracy: 0.8750
Epoch 3/100
1/1 [==============================] - 0s 9ms/step - loss: 0.3395 - accuracy: 0.8750
Epoch 4/100
1/1 [==============================] - 0s 10ms/step - loss: 0.3012 - accuracy: 0.8750
Epoch 5/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2721 - accuracy: 0.8750
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2505 - accuracy: 0.8750
Epoch 7/100
1/1 [==============================] - 0s 10ms/step - loss: 0.2347 - accuracy: 0.8750
Epoch 8/100
1/1 [==============================] - 0s 10ms/step - loss: 0.2233 - accuracy: 0.8750
Epoch 9/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2151 - accuracy: 0.8750
Epoch 10/100
1/1 [==============================] - 0s 8ms/step - loss: 0.2092 - accuracy: 0.8750
Epoch 11/100
1/1 [=====

In [ ]:
for i in x:
  prediction=model.predict(np.array([i]))
  print(f"input:- {i} predictio:- {round(prediction.flatten()[0])}")


1/1 [==============================] - 0s 32ms/step
input:- [0 0 0] predictio:- 0
1/1 [==============================] - 0s 30ms/step
input:- [0 0 1] predictio:- 1
1/1 [==============================] - 0s 43ms/step
input:- [0 1 0] predictio:- 1
1/1 [==============================] - 0s 31ms/step
input:- [0 1 1] predictio:- 1
1/1 [==============================] - 0s 34ms/step
input:- [1 0 0] predictio:- 1
1/1 [==============================] - 0s 22ms/step
input:- [1 0 1] predictio:- 1
1/1 [==============================] - 0s 20ms/step
input:- [1 1 0] predictio:- 1
1/1 [==============================] - 0s 22ms/step
input:- [1 1 1] predictio:- 1


In [ ]:
newdata=np.array([[0,0,1]])
prediction=model.predict(newdata)
print(f"input:- {newdata} predictio:- {round(prediction.flatten()[0])}")

1/1 [==============================] - 0s 54ms/step
input:- [[0 0 1]] predictio:- 1


### ***single layer perceptron***

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [ ]:
x=np.array([[2,8],
           [3,7],
           [4,6],
           [5,5],
           [6,4],
           [1,10],
           [7,3],
           [8,2],
           [2,9],
           [9,1]])
y=np.array([[0],
   [0],
   [1],
   [1],
   [1],
   [0],
   [1],
   [1],
   [0],
   [1]])

In [ ]:
model=Sequential([Dense(1,input_dim=2,activation='sigmoid')])
model.compile(optimizer=Adam(learning_rate=0.1),loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.fit(x,y,epochs=100,verbose=0)

In [ ]:
for i in x:
  prediction=model.predict(np.array([i]))
  print(f"input:- {i} predictio:- {round(prediction.flatten()[0])}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
input:- [2 8] predictio:- 0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
input:- [3 7] predictio:- 0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
input:- [4 6] predictio:- 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
input:- [5 5] predictio:- 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
input:- [6 4] predictio:- 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
input:- [ 1 10] predictio:- 0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
input:- [7 3] predictio:- 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
input:- [8 2] predictio:- 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
input:- [2 9] predictio:- 0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
input:- [9 1] predictio:- 1


In [ ]:
acc=model.evaluate(x,y)
print(f"Accuracy: {round(acc[1])}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.0134
Accuracy: 1


In [ ]:
test=[3,0]
model.predict(np.array([test]))
print(prediction.flatten()[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1.0


# ***Multi layer perceptron***

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

In [ ]:
iris=load_iris()
x=iris.data
y=iris.target
print(x)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
mlp=MLPClassifier(hidden_layer_sizes=(11,11,11),max_iter=500,random_state=25)
mlp.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(11, 11, 11), max_iter=500, random_state=25)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

y_pred = mlp.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.9777777777777777
Confusion Matrix:
[[17  0  0]
 [ 0 16  0]
 [ 0  1 11]]


In [ ]:
print(y_pred)

[0 1 2 2 2 2 2 0 1 1 0 0 0 2 0 2 2 2 1 1 1 1 2 0 0 2 1 2 2 0 2 1 2 0 2 2 1
 0 0 0 0 0 0 0 2]
